### Import pandas

In [1]:
import pandas as pd

In [2]:
url = 'https://en.wikipedia.org/wiki/List_of_most-played_video_games_by_player_count#cite_note-77'

### Read tables

In [3]:
tables = pd.read_html(url)
df1 = tables[1]
df1

,Game,Number,As of,Business model,Release date,Publisher(s),Ref.
0,Pac-Man Doodle,1 billion peak weekly players[a],May 2010,Free-to-play,"May 21, 2010",Namco / Google,[1]
1,CrossFire,660 million registered accounts,September 2018,Free-to-play,"May 3, 2007",Smilegate,[2]
2,Dungeon Fighter Online,600 million,June 2018,Free-to-play,August 2005,Nexon,[3]
3,PlayerUnknown's Battlegrounds,555 million[a],December 2019,Pay-to-play[b],"December 20, 2017",PUBG Corporation,[4]
4,Candy Crush Saga,500 million[a],June 2014,Free-to-play,"April 12, 2012",King,[5]
...,...,...,...,...,...,...,...
81,Star Wars: The Old Republic,10 million registered accounts,April 2018,Subscription,"December 20, 2011",Electronic Arts,[20]
82,Free Realms,10 million registered accounts,April 2018,Free-to-play,"April 28, 2009",Sony Online Entertainment,[20]
83,H1Z1,10 million,June 2018,Free-to-play,"February 28, 2018",Daybreak Game Company,[66]
84,Robocraft,10 million owners on Steam[g],July 2018,Free-to-play,"August 24, 2017",Freejam Games,[34]
85,Ark: Survival Evolved,10 million[a],November 2017,Pay-to-play,"August 29, 2017",Studio Wildcard,[67]

### Extract a list of numbers

In [4]:
number = []
for i in df1['Number']:
    if 'million' in i:
        number.append(i.split('million')[0])
    elif 'billion' in i:
        n = i.split('billion')[0]
        a = pd.to_numeric(n)*1000
        number.append(a)
    else:
        print("NA")
number = pd.to_numeric(number)
number

array([1000. ,  660. ,  600. ,  555. ,  500. ,  500. ,  400. ,  310. ,
        250. ,  230. ,  200. ,  200. ,  160. ,  120. ,  111. ,  100. ,
        100. ,  100. ,  100. ,  100. ,  100. ,  100. ,  100. ,  100. ,
        100. ,   91. ,   83. ,   83. ,   80. ,   80. ,   80. ,   75. ,
         71. ,   62. ,   60. ,   58. ,   50. ,   50. ,   50. ,   50. ,
         50. ,   50. ,   46. ,   43. ,   40. ,   35. ,   33. ,   33. ,
         32.5,   30. ,   30. ,   28.3,   26. ,   29. ,   27. ,   26. ,
         25. ,   24.9,   23. ,   20. ,   20. ,   18. ,   18. ,   18. ,
         17. ,   16. ,   15.9,   15. ,   15. ,   15. ,   15. ,   14. ,
         14. ,   13.9,   13.5,   13. ,   13. ,   12.6,   12.5,   11. ,
         10. ,   10. ,   10. ,   10. ,   10. ,   10. ])

### Number of players (in millions) of most popular games according to wiki

In [5]:
df_Game = pd.DataFrame(df1['Game'])
df_number = pd.DataFrame(number)

df1 = pd.concat([df_Game,df_number],axis=1)
df1.columns = ['Game','million_played']

df1.to_csv('wiki_most_played.csv')
df1

                             Game  million_played
0                  Pac-Man Doodle          1000.0
1                       CrossFire           660.0
2          Dungeon Fighter Online           600.0
3   PlayerUnknown's Battlegrounds           555.0
4                Candy Crush Saga           500.0
..                            ...             ...
81    Star Wars: The Old Republic            10.0
82                    Free Realms            10.0
83                           H1Z1            10.0
84                      Robocraft            10.0
85          Ark: Survival Evolved            10.0

[86 rows x 2 columns]